"""macOS-like silver theme tokens for the Flet UI shell."""

SILVER_BG = "#f1f3f5"
SILVER_PANEL = "#fafbfc"
SILVER_BORDER = "#d8dde3"
SILVER_TEXT = "#2c2f33"
SILVER_SUBTEXT = "#67707a"
ACCENT_BLUE = "#2f80ed"
ACCENT_RED = "#ff5f57"
ACCENT_YELLOW = "#ffbd2e"
ACCENT_GREEN = "#28c840"
