// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function GetProgress():Promise<main.ProgressInfo>;

export function GetSettings():Promise<main.Settings>;

export function GetTasks():Promise<Array<main.TaskDisplay>>;

export function ListScriptFiles():Promise<Array<backend.FileInfoExtended>>;

export function LoadScript(arg1:string):Promise<main.ScriptInfo>;

export function LoadScriptMerge(arg1:string):Promise<main.ScriptInfo>;

export function PauseAll():Promise<void>;

export function SelectScriptFile():Promise<string>;

export function SetSettings(arg1:main.Settings):Promise<void>;

export function StartAll():Promise<void>;
