// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function ListScriptFiles() {
  return window['go']['main']['App']['ListScriptFiles']();
}

export function LoadScript(arg1) {
  return window['go']['main']['App']['LoadScript'](arg1);
}

export function LoadScriptMerge(arg1) {
  return window['go']['main']['App']['LoadScriptMerge'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function SelectScriptFile() {
  return window['go']['main']['App']['SelectScriptFile']();
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}
